# Generated by Django 4.1.7 on 2023-04-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='guesses',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='score',
            name='raw_score',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
